use_frameworks!
# source 'https://github.com/delivero/iOS_PodsSpecs.git'
platform :ios, :deployment_target => "9.0"

target 'GBViewCollectionKitTests' do
    pod 'GBViewCollectionKit', :path => '../'
    
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "YES"
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = "YES"
        config.build_settings['GCC_NO_COMMON_BLOCKS'] = "YES"
        config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "YES"
    end
end
